{% set name = "orderedmultidict" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16a7ae8432e02cc987d2d6d5af2df5938258f87c870675c73ee77a0920e6f4a6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - six >=1.8.0

test:
  imports:
    - orderedmultidict
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/gruns/orderedmultidict
  license_file: LICENSE.md
  license: Unlicense
  license_family: Other
  summary: 'Ordered Multivalue Dictionary - omdict.'
  dev_url: https://github.com/gruns/orderedmultidict
  doc_url: https://github.com/gruns/orderedmultidict
  description: |
    omdict is an ordered multivalue dictionary that retains method parity with Python's dict and helps power furl.

extra:
  recipe-maintainers:
    - pmlandwehr
