# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nx/Zr01iR3SLBrZqFQtK+912yWAhQm9ipJ9iU0eJySCfy+iaPnWIVr3IG16UEZ0KfyPeQ6/kF+Gq/BFle2cQtebc5eXCTMCoizVKJW/yE+3xO/opuQ5t+VfpzVA1Citc3tU/T5ErYy63vjQxSvnKotpD7Gp32h0460eYP282CJ4WSkBAAEOD3swy6h379dG1duU8As0ilFxY2olI30vwA+8BpiDF3G4aflQFVOsHHKJVeV2ztbb9yLm2XDFe4Q4BNPAOSgEHB0d8e+hWIuhuvNRhZHBngA7bItQBgJn5JUKGjv8UbgvJYMs4QhlT5ar63t1fd2oSG75QCOcAMFvOINGVdVLohpaYG/7OEd0HyOSlW10w8O9t4vNtOvQUos9UmYEf4uko/S5V+egrN2Oo4DgFSge32YGTPp6GQMG1hrPng/GZtHfsWrYzlDVDb5+opOp9hIQ5T44EwOJ1xnUONBRv49KxYVz6ah51Vu9SPKeC7SWxbG7sj/wvIBkNyanKRNd/MWojIgg0uClsG+P55lgD5T+T9XwMEiJjJlmjTmlWGUZJWTkmXGYWchARbPD2VAB0Ku4v5UjCLWy6zH97YAkh4683VDbX74gNZwXU+3h3VfKL2fbpIBfr6+bqUDCeHB4iORhCrPCyFwVEEGVguTyby0NwgaHEbAq0UPpZw5A="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
