travis:
  secure:
    BINSTAR_TOKEN: nx/Zr01iR3SLBrZqFQtK+912yWAhQm9ipJ9iU0eJySCfy+iaPnWIVr3IG16UEZ0KfyPeQ6/kF+Gq/BFle2cQtebc5eXCTMCoizVKJW/yE+3xO/opuQ5t+VfpzVA1Citc3tU/T5ErYy63vjQxSvnKotpD7Gp32h0460eYP282CJ4WSkBAAEOD3swy6h379dG1duU8As0ilFxY2olI30vwA+8BpiDF3G4aflQFVOsHHKJVeV2ztbb9yLm2XDFe4Q4BNPAOSgEHB0d8e+hWIuhuvNRhZHBngA7bItQBgJn5JUKGjv8UbgvJYMs4QhlT5ar63t1fd2oSG75QCOcAMFvOINGVdVLohpaYG/7OEd0HyOSlW10w8O9t4vNtOvQUos9UmYEf4uko/S5V+egrN2Oo4DgFSge32YGTPp6GQMG1hrPng/GZtHfsWrYzlDVDb5+opOp9hIQ5T44EwOJ1xnUONBRv49KxYVz6ah51Vu9SPKeC7SWxbG7sj/wvIBkNyanKRNd/MWojIgg0uClsG+P55lgD5T+T9XwMEiJjJlmjTmlWGUZJWTkmXGYWchARbPD2VAB0Ku4v5UjCLWy6zH97YAkh4683VDbX74gNZwXU+3h3VfKL2fbpIBfr6+bqUDCeHB4iORhCrPCyFwVEEGVguTyby0NwgaHEbAq0UPpZw5A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
