travis:
  secure:
    BINSTAR_TOKEN: mvRWKqxHnX57AZi35jyAEp4w765DJz5wmAou4EcpT7MskHEfjbv6w6WG30CAJO/NysVG3brF8WNpSacjQ4tO9uTaNfGLk9JFQiQeGFoxyCSnZFxIlX2vz7Pn71yLhtIqWt9JYGI42CYcZ+5hsQH7Rbi1sNmwJnxcLHI5nTo2JlytGGlhyov7rZwDX9lWU5aQhNw/e429XAuaHcWzm+2rfzauyGoT8y2r38iV9lVczS+MqEDhPXEgGf5ljGV5A1zGwqowc/8i2ET7/8A2AJnUwM6QzGQOW7CqoR7QNaJmUuIpzyuMMilVzOQXNCGTqiSGC7zakN/Ergv/0kt7oDF1IhoEFlsoldxQD/hdaLp0PrTj0CYzMZQ8BHXektdHiYAF/PJeJTPHQ/gO8CrnnyKQ9jtQNaEOX2Q+BbTz813w3rsERZHUKLZtlwMsBaHbpMO1AWGlRnh1vdufMvVuAgA1Kp+/8hFCqUis415qPqpo+uF/zYe/2NF8IEmoTe5iapF6QtLeuqGE2eOnuuhrEEhFYKNcE6F7MqhAneRs5B1KD1oOTTEoL+aSzsuYmazFOejIEmdSMG6zw6yxGxD/sq0JG7CPgR+jchwhlzyARqdgE4SKJW3zT0Pq3cD7WNJPL2yjEC8OTXAIpT72mFpXPT4lcEcXe/6PQc+AIpqCG8LIlbs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
